{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "oracledb.name" . }}
  labels:
    app: {{ template "oracledb.name" . }}
    chart: {{ template "oracledb.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.dbPassword }}
  oracledb-system-password:  {{ .Values.dbPassword | b64enc | quote }}
  {{ else }}
  oracledb-system-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
{{- end }} 